# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 8
set_param chipscope.maxJobs 6
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7k160tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Y:/dev/open-ephys/ONI/riffa/fpga/devel/test-nereid/test-nereid.cache/wt [current_project]
set_property parent.project_path Y:/dev/open-ephys/ONI/riffa/fpga/devel/test-nereid/test-nereid.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part numato.com:nereid:part0:3.0 [current_project]
set_property ip_output_repo y:/dev/open-ephys/ONI/riffa/fpga/devel/test-nereid/test-nereid.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/functions.vh
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/riffa.vh
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/widths.vh
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/trellis.vh
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/types.vh
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tlp.vh
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/xilinx.vh
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/schedules.vh
}
read_verilog -library xil_defaultlib -sv Y:/dev/open-ephys/ONI/riffa/fpga/devel/test-nereid/test-nereid.srcs/sources_1/imports/kc705/riffa_wrapper_kc705.v
read_verilog -library xil_defaultlib {
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/async_fifo.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/async_fifo_fwft.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/channel.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/channel_128.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/channel_32.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/channel_64.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/chnl_tester.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/counter.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/cross_domain_signal.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/demux.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/engine_layer.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/ff.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/fifo.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/fifo_packer_128.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/fifo_packer_32.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/fifo_packer_64.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/interrupt.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/interrupt_controller.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/mux.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/offset_flag_to_one_hot.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/offset_to_mask.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/one_hot_mux.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/pipeline.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/ram_1clk_1w_1r.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/ram_2clk_1w_1r.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/recv_credit_flow_ctrl.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/register.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/registers.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/reorder_queue.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/reorder_queue_input.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/reorder_queue_output.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/reset_controller.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/reset_extender.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/riffa.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rotate.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rx_engine_classic.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rx_engine_ultrascale.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rx_port_128.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rx_port_32.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rx_port_64.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rx_port_channel_gate.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rx_port_reader.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rx_port_requester_mux.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rxc_engine_128.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rxc_engine_classic.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rxc_engine_ultrascale.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rxr_engine_128.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rxr_engine_classic.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/rxr_engine_ultrascale.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/scsdpram.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/sg_list_reader_128.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/sg_list_reader_32.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/sg_list_reader_64.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/sg_list_requester.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/shiftreg.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/sync_fifo.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/syncff.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/translation_xilinx.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_alignment_pipeline.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_data_fifo.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_data_pipeline.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_data_shift.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_engine.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_engine_classic.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_engine_selector.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_engine_ultrascale.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_hdr_fifo.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_multiplexer.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_multiplexer_128.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_multiplexer_32.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_multiplexer_64.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_port_128.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_port_32.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_port_64.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_port_buffer_128.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_port_buffer_32.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_port_buffer_64.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_port_channel_gate_128.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_port_channel_gate_32.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_port_channel_gate_64.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_port_monitor_128.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_port_monitor_32.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_port_monitor_64.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/tx_port_writer.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/txc_engine_classic.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/txc_engine_ultrascale.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/txr_engine_classic.v
  Y:/dev/open-ephys/ONI/riffa/fpga/riffa_hdl/txr_engine_ultrascale.v
  Y:/dev/open-ephys/ONI/riffa/fpga/devel/test-nereid/test-nereid.srcs/sources_1/imports/kc705/KC705_Gen2x8If128/hdl/KC705_Gen2x8If128.v
}
read_ip -quiet Y:/dev/open-ephys/ONI/riffa/fpga/devel/test-nereid/test-nereid.srcs/sources_1/ip/PCIeGen2x8If128/PCIeGen2x8If128.xci
set_property used_in_implementation false [get_files -all y:/dev/open-ephys/ONI/riffa/fpga/devel/test-nereid/test-nereid.srcs/sources_1/ip/PCIeGen2x8If128/source/PCIeGen2x8If128-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all y:/dev/open-ephys/ONI/riffa/fpga/devel/test-nereid/test-nereid.srcs/sources_1/ip/PCIeGen2x8If128/synth/PCIeGen2x8If128_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc Y:/dev/open-ephys/ONI/riffa/fpga/devel/test-nereid/test-nereid.srcs/constrs_1/new/nereid_riffa.xdc
set_property used_in_implementation false [get_files Y:/dev/open-ephys/ONI/riffa/fpga/devel/test-nereid/test-nereid.srcs/constrs_1/new/nereid_riffa.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top KC705_Gen2x8If128 -part xc7k160tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef KC705_Gen2x8If128.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file KC705_Gen2x8If128_utilization_synth.rpt -pb KC705_Gen2x8If128_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
